User story3
deriancastro/capstone-project pull request #13
Opened 2021-06-08 11:03 UTC by deriancastro

Hi, here is my third user-story, now die App has a goals page and can be navigated, I will be glad for your reviews - be kind :)

2021-06-08 11:36 UTC, badabam requested changes
You improved quite a few things, well done! But one thing _needs_ to be changed: the prop `isChecked` should be named different (see comments) as it is no boolean. And you **also** need a boolean `isChecked` that you can use for the `aria-checked`. 

Please fix that and push it in this PullRequest.

2021-06-08 11:36 UTC, badabam commented on src/App.js
> +  const goalsList = [
Please think about making this a JSON-File. You could directly add an `id` for each entry like that:
```js
  { text: 'Improve the performance of my left uchimata', id: '1' },
  { text: 'See the yoko tomoe tutorial', id: '2' },
    ```

2021-06-08 11:36 UTC, badabam commented on src/App.js
> +          onNavigate={showGoalsPage}
Good wording!

2021-06-08 11:36 UTC, badabam commented on src/App.js
> +    return console.log('The data will save in Localstorage')
This looks unfinished. Save it in localStorage and don't console.log about it. 😉

2021-06-08 11:36 UTC, badabam commented on src/components/Button.spec.js
> +    render(<Button onClick={noop}>Back</Button>)
Yes, exactly!

2021-06-08 11:36 UTC, badabam commented on src/components/Card.js
> +  onDetail: PropTypes.func,
Should have `.isRequired`

2021-06-08 11:36 UTC, badabam commented on src/components/Goal.js
> +  isChecked: PropTypes.func,
`isChecked` sounds like a boolean (it's a convention to prefix booleans with `is`, `has`, `does`). Please rename it. e.g. `onCheckGoal`

2021-06-08 11:36 UTC, badabam commented on src/components/Goal.js
> +        <input onChange={isChecked} type="checkbox" aria-checked="true" />
`aria-checked` should get different values (from a boolean called `isChecked` maybe?).

2021-06-08 11:36 UTC, badabam commented on src/pages/GoalsPage.js
> +            <li key={index}>
Better give the goals some ids and use them as the `key`.

2021-06-08 11:36 UTC, badabam commented on src/pages/GoalsPage.js
> +const Container = styled.section`
Maybe call it `Scroller` or `ScrollContainer` because that's the special thing about it?

2021-06-08 14:42 UTC, Tim-Pet reviewed
Nice one - I guess Jerries comments will do the trick here. Can't do much but agree with his comments 🥳

2021-06-08 14:42 UTC, Tim-Pet commented on src/pages/DetailPage.js
> +        <img src={judoImage} alt=""></img>
An alt text would be nice

2021-06-08 14:42 UTC, Tim-Pet commented on src/App.js
> +    return console.log('The data will save in Localstorage')
If you just console log in a function the user probably won't have a benefit from that function => implement the function only if you need it for the current us.

2021-06-08 14:42 UTC, Tim-Pet commented on src/pages/TutorialPage.spec.js
> +    expect(cardList).toHaveLength(8)
nice! 🚀

2021-06-08 21:22 UTC, deriancastro commented on src/App.js
> +  const goalsList = [
Done and I add a "isChecked" too

2021-06-08 21:23 UTC, deriancastro commented on src/App.js
> +          onNavigate={showGoalsPage}
good:)

2021-06-08 21:32 UTC, deriancastro commented on src/components/Goal.js
> +        <input onChange={isChecked} type="checkbox" aria-checked="true" />
Done, but I thought, that by render I could see some checkboxes 'checked':
![Bildschirmfoto 2021-06-08 um 23 05 26](https://user-images.githubusercontent.com/82398283/121260493-b7011480-c8b1-11eb-9967-376b05950839.png)

2021-06-08 21:33 UTC, deriancastro commented on src/pages/GoalsPage.js
> +const Container = styled.section`
done

2021-06-08 21:43 UTC, deriancastro commented on src/pages/GoalsPage.js
> +const Container = styled.section`
the commit with the changes is at the end, after the dialogues

2021-06-08 22:03 UTC, deriancastro commented on src/components/Goal.js
> +        <input onChange={isChecked} type="checkbox" aria-checked="true" />
It works just with 'checked'
![Bildschirmfoto 2021-06-09 um 00 02 20](https://user-images.githubusercontent.com/82398283/121263578-18c37d80-c8b6-11eb-95c7-9ae494b6f3b2.png)

2021-06-09 14:25 UTC, badabam approved these changes
Looks nice! Please update the json file import and then 🚢 it!

2021-06-09 14:25 UTC, badabam commented on src/App.js
> +  const [goalsList, setGoalsList] = useState(goalsJSON)
Please use `import` for importing your json file as well.

2021-06-09 14:25 UTC, badabam commented on src/App.js
> +    ])
Yes!

2021-06-09 15:16 UTC, deriancastro commented on src/App.js
> +    ])
OK, but Morten had to help me understand the mechanism

2021-06-09 17:11 UTC, merged